
一、变量
精确展开像宏一样；
全局;

变量的定义：
	var = 1
	var := $foo   只能使用前面已定义好了的变量，不能使用后面的变量。
	var ?= foo    如果var没有被定义过,那么var的值就是“foo”，否则什么也不做
	var += foo    追加变量值

变量的使用: 
	$var
    $(var)
    ${var}

特殊变量：
  VPATH = src:../headers
  指定其它目录来寻找依赖文件等。目录由“冒号”分隔

二、规则

语法：
目标: 依赖
	方法

最终目标：第一条规则的第一个目标



二、条件判断
ifeq (x,y)
...
else
...
endif

三、函数

函数调用：
  $(<function> <arguments>) 或 ${<function> <arguments>}

函数名和参数之间以“空格”，而分隔参数间以逗号“,”分隔


函数：

$(strip <string>)
名称:去空格函数——strip。
功能:去掉<string>字串中开头和结尾的空字符。
返回:返回被去掉空格的字符串值。

$(error <text ...>)
产生一个致命的错误，<text ...>是错误信息。会让 make 退出

$(warning <text ...>)
产生一个警告，不会让 make 退出。

--------------------------------------------------------------------------

关键字
include 

vpath 
  1、vpath <pattern> <directories>
    为符合模式<pattern>的文件指定搜索目录<directories>。
  2、vpath <pattern>
    清除符合模式<pattern>的文件的搜索目录。
  3、vpath
    清除所有已被设置好了的文件搜索目录。


--------------------------------------------------------------------------
Makefile.am
   |
   |automake
   |
Makefile.in
   |
   |configure
   |
Makefile

